#ifndef DPCONTROLLER_GLOBAL_H
#define DPCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DPCONTROLLER_LIBRARY)
#  define DPCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DPCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DPCONTROLLER_GLOBAL_H
