#ifndef DPMOORING_GLOBAL_H
#define DPMOORING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DPMOORING_LIBRARY)
#  define DPMOORINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DPMOORINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DPMOORING_GLOBAL_H
