/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * FourShipStateFcn.c
 *
 * Code generation for function 'FourShipStateFcn'
 *
 */

/* Include files */
#include "FourShipStateFcn.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void FourShipStateFcn(const real_T in1[24], const real_T in2[24],
                      real_T out1[24])
{
  real_T b_out1_tmp;
  real_T c_out1_tmp;
  real_T d_out1_tmp;
  real_T e_out1_tmp;
  real_T out1_tmp;
  real_T t10;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t26;
  real_T t27;
  real_T t28;
  real_T t29;
  /* FourShipStateFcn */
  /*     OUT1 = FourShipStateFcn(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.1.
   */
  /*     29-May-2022 11:10:57 */
  t10 = muDoubleScalarCos(in1[2]);
  t11 = muDoubleScalarCos(in1[8]);
  t12 = muDoubleScalarCos(in1[14]);
  t13 = muDoubleScalarCos(in1[20]);
  t26 = muDoubleScalarSin(in1[2]);
  t27 = muDoubleScalarSin(in1[8]);
  t28 = muDoubleScalarSin(in1[14]);
  t29 = muDoubleScalarSin(in1[20]);
  out1[0] = t10 * in1[3] - t26 * in1[4];
  out1[1] = t26 * in1[3] + t10 * in1[4];
  out1[2] = in1[5];
  t10 = in2[1] * muDoubleScalarCos(in2[4]);
  t26 = in2[2] * muDoubleScalarCos(in2[5]);
  out1[3] =
      (((in1[3] * -0.01 + t10 * 0.0014269406392694061) +
        t26 * 0.0014269406392694061) +
       in2[0] * muDoubleScalarCos(in2[3]) * 0.0014269406392694061) +
      in1[5] * (in1[5] * 140000.0 - in1[4] * 994000.0) * -1.426940639269406E-6;
  out1_tmp = in2[0] * muDoubleScalarSin(in2[3]);
  b_out1_tmp = in2[1] * muDoubleScalarSin(in2[4]);
  c_out1_tmp = in2[2] * muDoubleScalarSin(in2[5]);
  d_out1_tmp = in1[3] * in1[5];
  e_out1_tmp = in1[3] * in1[4];
  out1[4] =
      ((((in1[5] * -0.007045416178974943 - in1[4] * 0.025011227435361039) -
         t10 * 8.6611644213800846E-6) +
        t26 * 8.6611644213800846E-6) +
       ((out1_tmp * 0.000990384675421431 + b_out1_tmp * 0.00104484094476119) +
        c_out1_tmp * 0.00104484094476119)) +
      (d_out1_tmp * -0.70489771090350661 - e_out1_tmp * 0.00094053829938838549);
  out1[5] = ((((in1[5] * -0.0500224548707221 - in1[4] * 7.9714791063442632E-5) -
               t10 * 6.14942673917986E-5) +
              t26 * 6.14942673917986E-5) +
             (((out1_tmp * -0.0001111259473649811 +
                b_out1_tmp * 0.00027551356494730532) +
               c_out1_tmp * 0.00027551356494730532) +
              d_out1_tmp * 0.00094053829938838581)) +
            e_out1_tmp * -0.0066778219256575372;
  out1[6] = t11 * in1[9] - t27 * in1[10];
  out1[7] = t27 * in1[9] + t11 * in1[10];
  out1[8] = in1[11];
  t10 = in2[7] * muDoubleScalarCos(in2[10]);
  t26 = in2[8] * muDoubleScalarCos(in2[11]);
  out1[9] = (((in1[9] * -0.01 + t10 * 0.0014269406392694061) +
              t26 * 0.0014269406392694061) +
             in2[6] * muDoubleScalarCos(in2[9]) * 0.0014269406392694061) +
            in1[11] * (in1[11] * 140000.0 - in1[10] * 994000.0) *
                -1.426940639269406E-6;
  out1_tmp = in2[6] * muDoubleScalarSin(in2[9]);
  b_out1_tmp = in2[7] * muDoubleScalarSin(in2[10]);
  c_out1_tmp = in2[8] * muDoubleScalarSin(in2[11]);
  d_out1_tmp = in1[9] * in1[11];
  e_out1_tmp = in1[9] * in1[10];
  out1[10] =
      ((((in1[11] * -0.007045416178974943 - in1[10] * 0.025011227435361039) -
         t10 * 8.6611644213800846E-6) +
        t26 * 8.6611644213800846E-6) +
       ((out1_tmp * 0.000990384675421431 + b_out1_tmp * 0.00104484094476119) +
        c_out1_tmp * 0.00104484094476119)) +
      (d_out1_tmp * -0.70489771090350661 - e_out1_tmp * 0.00094053829938838549);
  out1[11] =
      ((((in1[11] * -0.0500224548707221 - in1[10] * 7.9714791063442632E-5) -
         t10 * 6.14942673917986E-5) +
        t26 * 6.14942673917986E-5) +
       (((out1_tmp * -0.0001111259473649811 +
          b_out1_tmp * 0.00027551356494730532) +
         c_out1_tmp * 0.00027551356494730532) +
        d_out1_tmp * 0.00094053829938838581)) +
      e_out1_tmp * -0.0066778219256575372;
  out1[12] = t12 * in1[15] - t28 * in1[16];
  out1[13] = t28 * in1[15] + t12 * in1[16];
  out1[14] = in1[17];
  t10 = in2[13] * muDoubleScalarCos(in2[16]);
  t26 = in2[14] * muDoubleScalarCos(in2[17]);
  out1[15] = (((in1[15] * -0.01 + t10 * 0.0014269406392694061) +
               t26 * 0.0014269406392694061) +
              in2[12] * muDoubleScalarCos(in2[15]) * 0.0014269406392694061) +
             in1[17] * (in1[17] * 140000.0 - in1[16] * 994000.0) *
                 -1.426940639269406E-6;
  out1_tmp = in2[12] * muDoubleScalarSin(in2[15]);
  b_out1_tmp = in2[13] * muDoubleScalarSin(in2[16]);
  c_out1_tmp = in2[14] * muDoubleScalarSin(in2[17]);
  d_out1_tmp = in1[15] * in1[17];
  e_out1_tmp = in1[15] * in1[16];
  out1[16] =
      ((((in1[17] * -0.007045416178974943 - in1[16] * 0.025011227435361039) -
         t10 * 8.6611644213800846E-6) +
        t26 * 8.6611644213800846E-6) +
       ((out1_tmp * 0.000990384675421431 + b_out1_tmp * 0.00104484094476119) +
        c_out1_tmp * 0.00104484094476119)) +
      (d_out1_tmp * -0.70489771090350661 - e_out1_tmp * 0.00094053829938838549);
  out1[17] =
      ((((in1[17] * -0.0500224548707221 - in1[16] * 7.9714791063442632E-5) -
         t10 * 6.14942673917986E-5) +
        t26 * 6.14942673917986E-5) +
       (((out1_tmp * -0.0001111259473649811 +
          b_out1_tmp * 0.00027551356494730532) +
         c_out1_tmp * 0.00027551356494730532) +
        d_out1_tmp * 0.00094053829938838581)) +
      e_out1_tmp * -0.0066778219256575372;
  out1[18] = t13 * in1[21] - t29 * in1[22];
  out1[19] = t29 * in1[21] + t13 * in1[22];
  out1[20] = in1[23];
  t10 = in2[19] * muDoubleScalarCos(in2[22]);
  t26 = in2[20] * muDoubleScalarCos(in2[23]);
  out1[21] = (((in1[21] * -0.01 + t10 * 0.0014269406392694061) +
               t26 * 0.0014269406392694061) +
              in2[18] * muDoubleScalarCos(in2[21]) * 0.0014269406392694061) +
             in1[23] * (in1[23] * 140000.0 - in1[22] * 994000.0) *
                 -1.426940639269406E-6;
  out1_tmp = in2[18] * muDoubleScalarSin(in2[21]);
  b_out1_tmp = in2[19] * muDoubleScalarSin(in2[22]);
  c_out1_tmp = in2[20] * muDoubleScalarSin(in2[23]);
  d_out1_tmp = in1[21] * in1[23];
  e_out1_tmp = in1[21] * in1[22];
  out1[22] =
      ((((in1[23] * -0.007045416178974943 - in1[22] * 0.025011227435361039) -
         t10 * 8.6611644213800846E-6) +
        t26 * 8.6611644213800846E-6) +
       ((out1_tmp * 0.000990384675421431 + b_out1_tmp * 0.00104484094476119) +
        c_out1_tmp * 0.00104484094476119)) +
      (d_out1_tmp * -0.70489771090350661 - e_out1_tmp * 0.00094053829938838549);
  out1[23] =
      ((((in1[23] * -0.0500224548707221 - in1[22] * 7.9714791063442632E-5) -
         t10 * 6.14942673917986E-5) +
        t26 * 6.14942673917986E-5) +
       (((out1_tmp * -0.0001111259473649811 +
          b_out1_tmp * 0.00027551356494730532) +
         c_out1_tmp * 0.00027551356494730532) +
        d_out1_tmp * 0.00094053829938838581)) +
      e_out1_tmp * -0.0066778219256575372;
}

/* End of code generation (FourShipStateFcn.c) */
