#ifndef DPENVIRONMENT_GLOBAL_H
#define DPENVIRONMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DPENVIRONMENT_LIBRARY)
#  define DPENVIRONMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DPENVIRONMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DPENVIRONMENT_GLOBAL_H
