/*
 * OneShipStateFcn.c
 *
 * Code generation for function 'OneShipStateFcn'
 *
 */

/* Include files */
#include "OneShipStateFcn.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <string.h>

/* Function Definitions */
void OneShipStateFcn(const real_T in1[6], const real_T in2[8], real_T out1[6])
{
  real_T t10;
  real_T t11;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  /* OneShipStateFcn */
  /*     OUT1 = OneShipStateFcn(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 9.1.
   */
  /*     22-Nov-2022 20:29:28 */
  t2 = muDoubleScalarCos(in2[4]);
  t3 = muDoubleScalarCos(in2[5]);
  t4 = muDoubleScalarCos(in2[6]);
  t5 = muDoubleScalarCos(in2[7]);
  t6 = muDoubleScalarCos(in1[2]);
  t7 = muDoubleScalarSin(in2[4]);
  t8 = muDoubleScalarSin(in2[5]);
  t9 = muDoubleScalarSin(in2[6]);
  t10 = muDoubleScalarSin(in2[7]);
  t11 = muDoubleScalarSin(in1[2]);
  out1[0] = t6 * in1[3] - t11 * in1[4];
  out1[1] = t11 * in1[3] + t6 * in1[4];
  out1[2] = in1[5];
  out1[3] = (((in1[3] * -0.04 + in2[0] * t2 * 1.6393442622950821E-5) +
              in2[1] * t3 * 1.6393442622950821E-5) +
             in2[2] * t4 * 1.6393442622950821E-5) +
            (in2[3] * t5 * 1.6393442622950821E-5 +
             in1[4] * in1[5] * 1.40983606557377);
  out1[4] =
      (((in1[4] * -0.05674418604651163 + in2[0] * t7 * 1.162790697674419E-5) +
        in2[1] * t8 * 1.162790697674419E-5) +
       in2[2] * t9 * 1.162790697674419E-5) +
      (in2[3] * t10 * 1.162790697674419E-5 -
       in1[3] * in1[5] * 0.70930232558139539);
  out1[5] = ((in1[5] * -0.070304169452928736 -
              in1[3] * in1[4] * 0.0002259131409155808) -
             in2[0] * (t2 * 50.0 - t7 * 75.0) * 9.03652563662323E-9) +
            ((in2[1] * (t3 * 50.0 + t8 * 75.0) * -9.03652563662323E-9 +
              in2[2] * (t4 * 50.0 - t9 * 75.0) * 9.03652563662323E-9) +
             in2[3] * (t5 * 50.0 + t10 * 75.0) * 9.03652563662323E-9);
}

/* End of code generation (OneShipStateFcn.c) */
